# Hunza@123 Hunza@123
    # hunzatestapi, neerajtesthunza@yopmail.com
# spring.data.mongodb.database=bezkoder_db
# spring.data.mongodb.port=27017
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      database: caterer_db
      uri: mongodb+srv://Hunza:Hunza%40123@cluster0.hbqno.mongodb.net/?retryWrites=true&w=majority
logging:
  file:
    name: catererapi.log
  logback:
    rollingpolicy:
      clean-history-on-start: 'true'
      total-size-cap: 10MB
      file-name-pattern: catererapi-%d{yyyy-MM-dd}.%i.log
      max-history: '30'
      max-file-size: 1MB
  level:
    root: info
hunza:
  logging:
    filter: true

